"""Aircall API Python SDK."""

from aircall.client import AircallClient
from aircall.exceptions import (
    AircallAPIError,
    AircallConnectionError,
    AircallError,
    AircallPermissionError,
    AircallTimeoutError,
    AuthenticationError,
    NotFoundError,
    RateLimitError,
    ServerError,
    UnprocessableEntityError,
    ValidationError,
)
from aircall.models import (
    AIVoiceAgent,
    ActionItemsContent,
    AnalyticsExport,
    Call,
    CallAIVoiceAgent,
    CallComment,
    Company,
    Contact,
    Content,
    ConversationIntelligence,
    ConversationIntelligenceParticipant,
    DialerCampaign,
    DialerCampaignPhoneNumber,
    Email,
    GroupMessage,
    IVROption,
    Integration,
    MediaDetail,
    Message,
    Number,
    NumberMessages,
    OutboundCallRequest,
    Participant,
    PhoneNumber,
    RealtimeTranscription,
    RealtimeTranscriptionCall,
    RealtimeTranscriptionUtterance,
    SmsTemplate,
    SummaryContent,
    Tag,
    Team,
    TopicsContent,
    User,
    UserAvailability,
    UserV2,
    UserV2Availability,
    Utterance,
    Webhook,
    WhatsAppLineStatus,
)
from aircall.logging_config import configure_logging
from aircall.pagination import Page, PageMeta

__all__ = [
    # Client
    "AircallClient",
    # Base exceptions
    "AircallError",
    "AircallAPIError",
    # API exceptions
    "AuthenticationError",
    "AircallPermissionError",
    "NotFoundError",
    "ValidationError",
    "UnprocessableEntityError",
    "RateLimitError",
    "ServerError",
    # Connection exceptions
    "AircallConnectionError",
    "AircallTimeoutError",
    # Models
    "AIVoiceAgent",
    "ActionItemsContent",
    "AnalyticsExport",
    "Call",
    "CallAIVoiceAgent",
    "CallComment",
    "Company",
    "Contact",
    "Content",
    "ConversationIntelligence",
    "ConversationIntelligenceParticipant",
    "DialerCampaign",
    "DialerCampaignPhoneNumber",
    "Email",
    "GroupMessage",
    "IVROption",
    "Integration",
    "MediaDetail",
    "Message",
    "Number",
    "NumberMessages",
    "OutboundCallRequest",
    "Participant",
    "PhoneNumber",
    "RealtimeTranscription",
    "RealtimeTranscriptionCall",
    "RealtimeTranscriptionUtterance",
    "SmsTemplate",
    "SummaryContent",
    "Tag",
    "Team",
    "TopicsContent",
    "User",
    "UserAvailability",
    "UserV2",
    "UserV2Availability",
    "Utterance",
    "Webhook",
    "WhatsAppLineStatus",
    # Pagination
    "Page",
    "PageMeta",
    # Logging
    "configure_logging",
]
