name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: I've also thought about...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Code Example
      description: If applicable, provide a code example of how you'd like to use this feature
      render: python
      placeholder: |
        from aircall import AircallClient

        client = AircallClient(api_id="...", api_token="...")
        # Example usage of the proposed feature
    validations:
      required: false

  - type: dropdown
    id: api-endpoint
    attributes:
      label: Related API Endpoint
      description: Which Aircall API resource is this related to?
      options:
        - Calls
        - Contacts
        - Numbers
        - Users
        - Teams
        - Tags
        - Messages
        - Webhooks
        - Integrations
        - Dialer Campaigns
        - Companies
        - AI Voice Agents
        - Conversation Intelligence
        - Other
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
      placeholder: Any additional information...
    validations:
      required: false
